inherit_from: .rubocop_todo.yml
AllCops:
  TargetRubyVersion: 2.6

Style/FrozenStringLiteralComment:
  Enabled: false
  
Layout/AlignArray:
  Exclude:
    - 'Base Ruby/lesson_3_OOP/lib/menu/context.rb'

Metrics/AbcSize:
  Max: 40

Metrics/ClassLength:
  Exclude:
    - 'Base Ruby/lesson_3_OOP/lib/menu/railroad.rb'

Style/Documentation:
  Enabled: false

Lint/UnusedBlockArgument:
  Exclude:
    - 'Base Ruby/lesson_3_OOP/lib/modules/accessor.rb'

Lint/UselessAssignment:
  Exclude:
    - 'Base Ruby/lesson_3_OOP/lib/modules/validation.rb'
